[build]
command = "npm ci && npm run build"
publish = "build/client"

[build.environment]
NPM_CONFIG_ENGINE_STRICT = "true"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_PROGRESS = "false"
NPM_CONFIG_UPDATE_NOTIFIER = "false"
SKIP_DEPENDENCY_INSTALL = "true"
