# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10a8926387f7ea9e09395b64b1f798c2"
name = "woood"
handle = "woood"
application_url = "https://woood-production.leander-4e0.workers.dev/"
embedded = false

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_checkouts,write_delivery_customizations,write_orders"

[auth]
redirect_urls = [
  "https://woood-production.leander-4e0.workers.dev/auth/callback"
]