# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10a8926387f7ea9e09395b64b1f798c2"
name = "woood"
handle = "woood"
application_url = "https://strips-insured-love-potentially.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "webfluencer-panda.myshopify.com"
scope = "read_products,write_products,write_checkouts,write_delivery_customizations,write_orders"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_checkouts,write_delivery_customizations,write_orders"

[auth]
redirect_urls = ["https://strips-insured-love-potentially.trycloudflare.com/auth/callback", "https://strips-insured-love-potentially.trycloudflare.com/auth/shopify/callback", "https://strips-insured-love-potentially.trycloudflare.com/api/auth/callback"]
