# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1c7701d2e09d4ede7616f35e13d472ef"
application_url = "https://woood-staging.leander-4e0.workers.dev"
embedded = true
name = "woood CF (staging)"
handle = "woood-2"

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
scopes = "read_products, write_products, write_app_proxy, write_checkouts, write_delivery_customizations, write_orders"
use_legacy_install_flow = false

[app_proxy]
url = "https://woood-staging.leander-4e0.workers.dev/apps/woood"
subpath = "woood"
prefix = "apps"

[auth]
redirect_urls = [
  "https://woood-staging.leander-4e0.workers.dev/auth/callback",
  "https://woood-staging.leander-4e0.workers.dev/auth/shopify/callback",
  "https://woood-staging.leander-4e0.workers.dev/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true
dev_store_url = "webfluencer-panda.myshopify.com"

[webhooks]
api_version = "2025-07"
  [[webhooks.subscriptions]]
  uri = "/shopify/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  topics = [ "app/scopes_update", "app/uninstalled" ]

[pos]
embedded = false
