# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d22869905669a81f0678f4549458a4d7"
organization_id = "159276453"
name = "woood-delivery-date-picker"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
