# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "woood-delivery-dates"
client_id = "1c7701d2e09d4ede7616f35e13d472ef"
application_url = "https://woood-delivery-api.leander-4e0.workers.dev"
embedded = true

[access_scopes]
scopes = "read_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://woood-delivery-api.leander-4e0.workers.dev/auth/callback",
  "https://woood-delivery-api.leander-4e0.workers.dev/auth/shopify/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false

[build]
include_config_on_deploy = true

# Extensions automatically inherit app context
[[extensions]]
type = "checkout_ui_extension"
name = "delivery-date-picker"
handle = "delivery-date-picker"

[[extensions]]
type = "function"
name = "shipping-method-filter"
handle = "shipping-method-filter"
