# Shopify app configuration for production environment
name = "woood-delivery-date-picker"
handle = "woood-delivery-date-picker"
client_id = "10a8926387f7ea9e09395b64b1f798c2"
application_url = "https://your-app-domain.com"
embedded = true
include_config_on_deploy = true

[auth]
redirect_urls = ["https://your-app-domain.com/auth/callback"]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false

[access_scopes]
scopes = "read_checkouts,write_checkouts,read_orders,write_orders,read_products,write_delivery_customizations,read_delivery_customizations"

[app_preferences]
url = "https://woood.gadget.app/preferences"

[app_proxy]
url = "https://woood.gadget.app/proxy"
subpath = "apps"
prefix = "a"

[build]
include_config_on_deploy = true
