# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
uid = "0f84f69f-bd5e-3dd2-55fb-4844bd456e469c48c67d"
type = "ui_extension"
name = "date-picker"
handle = "date-picker"
description = "Delivery date picker for Netherlands customers with DutchNed API integration"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension's source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
target = "purchase.checkout.shipping-option-list.render-after"
module = "./src/index.tsx"

[extensions.capabilities]
# Gives your extension access to directly query Shopify's storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
# api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

[[extensions.metafields]]
namespace = "erp"
key = "levertijd"

[[extensions.metafields]]
namespace = "custom"
key = "ShippingMethod2"


# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "extension_mode"
type = "single_line_text_field"
name = "Extension Mode"
description = "Choose how the extension behaves (Default: Full)"
[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"Disabled\", \"Shipping Data Only\", \"Date Picker Only\", \"Full\"]"

[[extensions.settings.fields]]
key = "date_picker_filtering"
type = "single_line_text_field"
name = "Date Picker Filtering"
description = "No Filtering: Show all available dates | ERP Filtered: Only show dates after product minimum delivery times (Default: ERP Filtered)"
[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"No Filtering\", \"ERP Filtered\"]"

[[extensions.settings.fields]]
key = "only_show_if_in_stock"
type = "boolean"
name = "Only show if in stock"
default = false
description = "Only show the date picker if all products in the cart are in stock (Default: false)"

[[extensions.settings.fields]]
key = "hide_picker_within_days"
type = "number_integer"
name = "Hide Picker Within Days"
description = "Hide date picker if products can be delivered within this many days (0 = always show picker) (Default: 14)"

[[extensions.settings.fields]]
key = "max_dates_to_show"
type = "number_integer"
name = "Max Dates to Show"
description = "Maximum number of delivery dates to display in the picker (Default: 15)"

[[extensions.settings.fields]]
key = "active_country_codes"
type = "single_line_text_field"
name = "Active Country Codes"
description = "Comma-separated country codes where date picker is active (e.g., NL,BE,DE) (Default: NL)"

[[extensions.settings.fields]]
key = "enable_mock_mode"
type = "boolean"
name = "Enable Mock Dates"
default = false
description = "Enable mock delivery dates for testing (fallback when API is unavailable) (Default: false)"

[[extensions.settings.fields]]
key = "preview_mode"
type = "boolean"
name = "Preview Mode"
default = false
description = "Show preview-only UI (for testing in Checkout Editor)"


