# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
uid = "0f84f69f-bd5e-3dd2-55fb-4844bd456e469c48c67d"
type = "ui_extension"
name = "date-picker"
handle = "date-picker"
description = "Delivery date picker for Netherlands customers with DutchNed API integration"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension's source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
target = "purchase.checkout.shipping-option-list.render-after"
module = "./src/index.tsx"

[extensions.capabilities]
# Gives your extension access to directly query Shopify's storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
# api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

[[extensions.metafields]]
namespace = "erp"
key = "levertijd"

[[extensions.metafields]]
namespace = "custom"
key = "ShippingMethod2"


# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
[[extensions.settings.fields]]
key = "hide_date_picker"
type = "boolean"
name = "Hide Date Picker"
default = false
description = "Completely hide the delivery date picker from checkout"

[[extensions.settings.fields]]
key = "enable_mock_mode"
type = "boolean"
name = "Enable Mock Dates"
description = "Enable mock delivery dates for testing (fallback when API is unavailable)"

[[extensions.settings.fields]]
key = "enable_week_number_filtering"
type = "boolean"
name = "Enable Week Number Filtering"
default = true
description = "Enable filtering of delivery dates based on product ERP delivery times"
