# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "47a8674c4821a34f563505aa4d3d4b71"
name = "woood-dev"
application_url = "https://woood--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
# Gadget manages all your scopes, webhooks and api versioning for your app
# As such, this line should not be changed unless you are working with
# Shopify managed installations. Read more at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml
include_config_on_deploy = true

[auth]
redirect_urls = ["https://woood--development.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-04"
