name = "woood-production"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set via wrangler secret)
# DUTCHNED_API_URL
# DUTCHNED_API_CREDENTIALS
# SHOPIFY_APP_CLIENT_ID
# SHOPIFY_APP_CLIENT_SECRET
# SHOPIFY_APP_URL
# External API integration environment variables
# SHOPIFY_ADMIN_API_ACCESS_TOKEN
# SHOPIFY_STORE_URL
# DUTCH_FURNITURE_BASE_URL
# DUTCH_FURNITURE_API_KEY

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "WOOOD_KV"
id = "17189fd27a034c548fd662aa7ffa8415"

[[kv_namespaces]]
binding = "STORE_LOCATOR_STATUS"
id = "e03ccea949a342ed8ad81e4d0e1b2478"

[[kv_namespaces]]
binding = "EXPERIENCE_CENTER_STATUS"
id = "fc265ea8b60f4e3aa8b2c3ac3e89eb69"

[build]
command = "npm run build"

[env.production]
name = "woood-production"

[env.production.vars]
CORS_ORIGINS = "https://*.myshopify.com,https://checkout.shopify.com"

[[env.production.kv_namespaces]]
binding = "WOOOD_KV"
id = "17189fd27a034c548fd662aa7ffa8415"

[[env.production.kv_namespaces]]
binding = "STORE_LOCATOR_STATUS"
id = "e03ccea949a342ed8ad81e4d0e1b2478"

[[env.production.kv_namespaces]]
binding = "EXPERIENCE_CENTER_STATUS"
id = "fc265ea8b60f4e3aa8b2c3ac3e89eb69"

[env.staging]
name = "woood-staging"

[env.staging.vars]
CORS_ORIGINS = "https://*.myshopify.com,https://checkout.shopify.com"

[[env.staging.kv_namespaces]]
binding = "WOOOD_KV"
id = "51fa115a98f44c4d896d3fd99d942d17"

[[env.staging.kv_namespaces]]
binding = "STORE_LOCATOR_STATUS"
id = "e03ccea949a342ed8ad81e4d0e1b2478"

[[env.staging.kv_namespaces]]
binding = "EXPERIENCE_CENTER_STATUS"
id = "fc265ea8b60f4e3aa8b2c3ac3e89eb69"

# Cron triggers for scheduled tasks
[env.staging.triggers]
crons = ["0 */6 * * *"] # Runs every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)

[env.production.triggers]
crons = ["0 */6 * * *"] # Runs every 6 hours (00:00, 06:00, 12:00, 18:00 UTC)