name = "woood-production"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set via wrangler secret)
# DUTCHNED_API_URL
# DUTCHNED_API_CREDENTIALS
# SHOPIFY_APP_CLIENT_ID
# SHOPIFY_APP_CLIENT_SECRET
# SHOPIFY_APP_URL

[[kv_namespaces]]
binding = "WOOOD_KV"
id = "17189fd27a034c548fd662aa7ffa8415"

[build]
command = "npm run build"

[env.production]
name = "woood-production"

[env.production.vars]
CORS_ORIGINS = "https://*.myshopify.com,https://checkout.shopify.com"

[[env.production.kv_namespaces]]
binding = "WOOOD_KV"
id = "17189fd27a034c548fd662aa7ffa8415"

[env.staging]
name = "woood-staging"

[env.staging.vars]
CORS_ORIGINS = "https://*.myshopify.com,https://checkout.shopify.com"

[[env.staging.kv_namespaces]]
binding = "WOOOD_KV"
id = "placeholder-kv-namespace-id"