name: Cloudflare
name: Cloudflare

on:
  push:
    branches: ['**']
  workflow_dispatch: {}

env:
  NODE_VERSION: '20'
  BRANCH_STAGING: ${{ vars.BRANCH_STAGING || 'staging' }}
  BRANCH_PRODUCTION: ${{ vars.BRANCH_PRODUCTION || 'production' }}

jobs:
  deploy-staging:
    name: Deploy (Staging)
    if: ${{ github.ref == format('refs/heads/{0}', (vars.BRANCH_STAGING || 'staging')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
        env:
          NPM_CONFIG_ENGINE_STRICT: true
          NPM_CONFIG_FUND: false
          NPM_CONFIG_PROGRESS: false
      - name: Build web (React Router)
        run: npm run build:web
      - name: Inject runtime vars into built wrangler config
        run: |
          node -e "
            const fs = require('fs');
            const p = 'build/server/wrangler.json';
            const j = JSON.parse(fs.readFileSync(p,'utf8'));
            j.vars = j.vars || {};
            j.vars.DUTCH_FURNITURE_BASE_URL = process.env.DFB;
            j.vars.DUTCHNED_API_URL = process.env.DNA;
            fs.writeFileSync(p, JSON.stringify(j, null, 2));
            console.log('Updated vars in', p);
          "
        env:
          DFB: ${{ vars.DUTCH_FURNITURE_BASE_URL }}
          DNA: ${{ vars.DUTCHNED_API_URL }}
      - name: Install Wrangler
        run: npm i -g wrangler@4.30.0
      - name: Deploy Worker (staging)
        run: wrangler deploy -c build/server/wrangler.json --keep-vars
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

  deploy-production:
    name: Deploy (Production)
    if: ${{ github.ref == format('refs/heads/{0}', (vars.BRANCH_PRODUCTION || 'production')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
        env:
          NPM_CONFIG_ENGINE_STRICT: true
          NPM_CONFIG_FUND: false
          NPM_CONFIG_PROGRESS: false
      - name: Build web (React Router)
        run: npm run build:web
      - name: Inject runtime vars into built wrangler config
        run: |
          node -e "
            const fs = require('fs');
            const p = 'build/server/wrangler.json';
            const j = JSON.parse(fs.readFileSync(p,'utf8'));
            j.vars = j.vars || {};
            j.vars.DUTCH_FURNITURE_BASE_URL = process.env.DFB;
            j.vars.DUTCHNED_API_URL = process.env.DNA;
            fs.writeFileSync(p, JSON.stringify(j, null, 2));
            console.log('Updated vars in', p);
          "
        env:
          DFB: ${{ vars.DUTCH_FURNITURE_BASE_URL }}
          DNA: ${{ vars.DUTCHNED_API_URL }}
      - name: Install Wrangler
        run: npm i -g wrangler@4.30.0
      - name: Deploy Worker (production)
        run: wrangler deploy -c build/server/wrangler.json --keep-vars
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


