name: Deploy (Staging)

on:
  push:
    branches:
      - staging
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 22
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build web (React Router)
        run: npm run build:web

      - name: Build app (Shopify CLI)
        run: npm run build

      - name: Deploy Cloudflare Worker (staging)
        if: ${{ vars.CF_GIT_INTEGRATION != 'true' }}
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy -c wrangler.json --keep-vars

      - name: Read package version
        id: pkg
        run: |
          VERSION=$(node -e "process.stdout.write(require('./package.json').version)")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Deploy Shopify App (staging)
        env:
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_PARTNERS_TOKEN }}
          SHOPIFY_CLI_TTY: 0
        run: >-
          npx shopify app deploy
          --client-id ${{ vars.SHOPIFY_APP_CLIENT_ID }}
          --force
          --message "${{ github.ref_name }}:${{ steps.pkg.outputs.version }}"
          --version "${{ github.sha }}"


