name: (Deprecated) Deploy Combined

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use 'Deploy (Staging)' or 'Deploy (Production)'."
