name: DEPRECATED: Deploy (Production)

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Use .github/workflows/cloudflare.yml and .github/workflows/shopify.yml instead."


